[General]
__userfile__=true
lock_screen_before_power_actions=false
window_manager=openbox

[Environment]
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0

[Keyboard]
layout="us,ua"
model=pc86
options=terminate:ctrl_alt_bksp, grp:win_space_toggle
variant=","

[Touchpad]
SynPS%252F2%2520Synaptics%2520TouchPad\accelSpeed=0
SynPS%252F2%2520Synaptics%2520TouchPad\disableWhileTypingEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\dragLockEnabled=0
SynPS%252F2%2520Synaptics%2520TouchPad\naturalScrollingEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\scrollingMethodEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tapToDragEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tappingEnabled=0
